---
swagger: "2.0"
info:
  x-ibm-name: "myloopbackapi"
  title: "myLoopbackAPI"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/"
consumes:
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        title: "gatewayscript"
        version: "1.0.0"
        source: "session.output.write('Hello');\napim.output('*/*');"
  phase: "realized"
paths:
  /myloopbackapi:
    get:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
